# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "test01" do |test01|
    test01.vm.box = "jeqo/centos-7"

    test01.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "512"
    end

    test01.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "install-oracle-java-8-centos-7.yml"
      ansible.galaxy_role_file = "roles.yml"
    end
  end

  config.vm.define "test02" do |test02|
    test02.vm.box = "jeqo/centos-7"

    test02.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "512"
    end

    test02.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "install-oracle-java-7-centos-7.yml"
      ansible.galaxy_role_file = "roles.yml"
    end
  end
end
